quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/quarkusdb

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8180/realms/caixaverso-dev
quarkus.oidc.client-id=quarkus-api
quarkus.oidc.credentials.secret=wq48XiZlGCklc8ltUdLwk8ztQmI9nCJ0
quarkus.oidc.token.issuer=caixaverso
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none
quarkus.dev.test.continuous-testing=disabled


