quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/quarkusdb

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8180/realms/caixaverso
quarkus.oidc.client-id=produto-api
quarkus.oidc.credentials.secret=<seu-client-secret> # se for confidencial
quarkus.oidc.token.issuer=caixaverso
quarkus.oidc.application-type=service
quarkus.http.auth.permission.admin.paths=/produtos,/produtos/*,/produtos/{id}
quarkus.http.auth.permission.admin.policy=authenticated